### ISSUE TITLE
Add usage instructions

### ISSUE THREAD

**Issue by loopmode** [epsitec/Tools-RecursiveDelete#2]
Hi
The tool looks great, but it is not obvious, how to actually use it :)

**Comment by epsitec** [comment]
You are right. I should add a blurb when the tool is launched without any arguments...

**Comment by loopmode** [comment]
Btw i currently use a globally installed rimraf, seems to do the job

**Comment by epsitec** [comment]
Fixed by commit cf922a2 (version 1.2.1537.0).
